development:
  clients:
    default:
      database: booklist_dev
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
production:
  clients:
    default:
      database: booklist_dev
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1